#!/usr/bin/env python3
from pathlib import Path

# Template filenames
XML_TEMPLATE_PATH = Path("relax_temp.xml")
FLAGS_TEMPLATE_PATH = Path("flags_relax_temp")

# Sweep 1: vary relax_repack_distance, fix minimize=10000
REPACK_DISTANCES = [0, 3, 6, 9, 12, 15]
FIXED_MIN_DISTANCE_FOR_REPACK_SWEEP = 10000

# Sweep 2: vary relax_minimize_distance, fix repack=10000
MINIMIZE_DISTANCES = [5, 10, 15, 20, 25, 30, 35, 40]
FIXED_REPACK_DISTANCE_FOR_MIN_SWEEP = 10000

RUN_SCRIPT_NAME = "run_all_relax.sh"


def load_templates():
    if not XML_TEMPLATE_PATH.is_file():
        raise FileNotFoundError(f"Cannot find XML template: {XML_TEMPLATE_PATH}")
    if not FLAGS_TEMPLATE_PATH.is_file():
        raise FileNotFoundError(f"Cannot find flags template: {FLAGS_TEMPLATE_PATH}")

    xml_template = XML_TEMPLATE_PATH.read_text()
    flags_template = FLAGS_TEMPLATE_PATH.read_text()
    return xml_template, flags_template


def make_xml(xml_template: str, repack: int, minimize: int, xml_name: str):
    xml_contents = (
        xml_template
        .replace("{relax_repack_distance}", str(repack))
        .replace("{relax_minimize_distance}", str(minimize))
    )
    Path(xml_name).write_text(xml_contents)


def update_flags(flags_template: str, xml_filename: str, sc_filename: str, prefix: str) -> str:
    """
    Update the flags template:
      - -parser:protocol <xmlfile>
      - -out:file:scorefile <scorefile.sc>
      - -out:prefix <prefix_>
      - -s prepare_gfp_raw_0001.pdb
    """
    lines = flags_template.splitlines()
    new_lines = []

    found_protocol = False
    found_scorefile = False
    found_prefix = False
    found_s_flag = False

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("-parser:protocol"):
            new_lines.append(f"-parser:protocol {xml_filename}")
            found_protocol = True
            continue

        if stripped.startswith("-out:file:scorefile"):
            new_lines.append(f"-out:file:scorefile {sc_filename}")
            found_scorefile = True
            continue

        if stripped.startswith("-out:prefix"):
            new_lines.append(f"-out:prefix {prefix}")
            found_prefix = True
            continue

        if stripped.startswith("-s "):
            new_lines.append("-s prepare_gfp_raw_0001.pdb")
            found_s_flag = True
            continue

        new_lines.append(line)

    if not found_protocol:
        new_lines.append(f"-parser:protocol {xml_filename}")

    if not found_scorefile:
        new_lines.append(f"-out:file:scorefile {sc_filename}")

    if not found_prefix:
        new_lines.append(f"-out:prefix {prefix}")

    if not found_s_flag:
        new_lines.append("-s prepare_gfp_raw_0001.pdb")

    return "\n".join(new_lines) + "\n"


def main():
    xml_template, flags_template = load_templates()
    runs = []  # list of (flags_filename, log_filename)

    # -----------------------------
    # Sweep 1: repack distances
    # -----------------------------
    for repack in REPACK_DISTANCES:
        minimize = FIXED_MIN_DISTANCE_FOR_REPACK_SWEEP

        xml_name = f"relax_r{repack}_m{minimize}.xml"
        flags_name = f"flags_r{repack}_m{minimize}"  # no extension
        sc_name = f"relax_r{repack}_m{minimize}.sc"
        log_name = f"flags_r{repack}_m{minimize}.log"
        prefix = f"flags_r{repack}_m{minimize}_"

        make_xml(xml_template, repack, minimize, xml_name)

        flags_contents = update_flags(flags_template, xml_name, sc_name, prefix)
        Path(flags_name).write_text(flags_contents)

        runs.append((flags_name, log_name))

    # -----------------------------
    # Sweep 2: minimization distances
    # -----------------------------
    for minimize in MINIMIZE_DISTANCES:
        repack = FIXED_REPACK_DISTANCE_FOR_MIN_SWEEP

        xml_name = f"relax_r{repack}_m{minimize}.xml"
        flags_name = f"flags_r{repack}_m{minimize}"
        sc_name = f"relax_r{repack}_m{minimize}.sc"
        log_name = f"flags_r{repack}_m{minimize}.log"
        prefix = f"flags_r{repack}_m{minimize}_"

        make_xml(xml_template, repack, minimize, xml_name)

        flags_contents = update_flags(flags_template, xml_name, sc_name, prefix)
        Path(flags_name).write_text(flags_contents)

        runs.append((flags_name, log_name))

    # -----------------------------
    # Write shell submission script
    # -----------------------------
    lines = [
        "#!/bin/bash",
        "set -e",
        "",
        "# Auto-generated by make_relax_sweep.py",
        "",
    ]

    for flags_name, log_name in runs:
        lines.append(f"echo 'Running {flags_name} -> {log_name}'")
        lines.append(f"rosetta_scripts @{flags_name} > {log_name} 2>&1")
        lines.append("")

    Path(RUN_SCRIPT_NAME).write_text("\n".join(lines) + "\n")
    print(f"Generated {len(runs)} XML/flags pairs and {RUN_SCRIPT_NAME}")


if __name__ == "__main__":
    main()

