#!/bin/bash
set -e

# Auto-generated by make_relax_sweep.py

echo 'Running flags_r0_m10000 -> flags_r0_m10000.log'
rosetta_scripts @flags_r0_m10000 > flags_r0_m10000.log 2>&1

echo 'Running flags_r3_m10000 -> flags_r3_m10000.log'
rosetta_scripts @flags_r3_m10000 > flags_r3_m10000.log 2>&1

echo 'Running flags_r6_m10000 -> flags_r6_m10000.log'
rosetta_scripts @flags_r6_m10000 > flags_r6_m10000.log 2>&1

echo 'Running flags_r9_m10000 -> flags_r9_m10000.log'
rosetta_scripts @flags_r9_m10000 > flags_r9_m10000.log 2>&1

echo 'Running flags_r12_m10000 -> flags_r12_m10000.log'
rosetta_scripts @flags_r12_m10000 > flags_r12_m10000.log 2>&1

echo 'Running flags_r15_m10000 -> flags_r15_m10000.log'
rosetta_scripts @flags_r15_m10000 > flags_r15_m10000.log 2>&1

echo 'Running flags_r10000_m5 -> flags_r10000_m5.log'
rosetta_scripts @flags_r10000_m5 > flags_r10000_m5.log 2>&1

echo 'Running flags_r10000_m10 -> flags_r10000_m10.log'
rosetta_scripts @flags_r10000_m10 > flags_r10000_m10.log 2>&1

echo 'Running flags_r10000_m15 -> flags_r10000_m15.log'
rosetta_scripts @flags_r10000_m15 > flags_r10000_m15.log 2>&1

echo 'Running flags_r10000_m20 -> flags_r10000_m20.log'
rosetta_scripts @flags_r10000_m20 > flags_r10000_m20.log 2>&1

echo 'Running flags_r10000_m25 -> flags_r10000_m25.log'
rosetta_scripts @flags_r10000_m25 > flags_r10000_m25.log 2>&1

echo 'Running flags_r10000_m30 -> flags_r10000_m30.log'
rosetta_scripts @flags_r10000_m30 > flags_r10000_m30.log 2>&1

echo 'Running flags_r10000_m35 -> flags_r10000_m35.log'
rosetta_scripts @flags_r10000_m35 > flags_r10000_m35.log 2>&1

echo 'Running flags_r10000_m40 -> flags_r10000_m40.log'
rosetta_scripts @flags_r10000_m40 > flags_r10000_m40.log 2>&1

