universe = vanilla
+WantFlocking = true
+WantGlideIn = true


container_image = osdf:///chtc/staging/bcjohnson7/metl_sim.sif

log = output/condor_logs/rosetta_$(Cluster)_$(Process).log
error = output/condor_logs/rosetta_$(Cluster)_$(Process).err
output = output/condor_logs/rosetta_$(Cluster)_$(Process).out


requirements = (Arch == "X86_64") && (has_avx == true) && (OpSys=="LINUX") && (GlideIN_Site =!= "FNAL")
executable = run_docker.sh

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = run.sh, pass.txt, code.tar.gz, args/$(Process).txt, energize_args.txt
transfer_output_files = output

request_cpus = 1
request_memory = 3GB
request_disk = 20GB

environment = "CLUSTER=$(Cluster) PROCESS=$(Process) RUNNINGON=$$(Name) GITHUB_TAG=$ENV(GITHUB_TAG) PYSCRIPT=$ENV(PYSCRIPT)"

# when submitting more than 10k jobs this will prevent the scheduler from getting overloaded
max_idle = 1000

# set it so jobs that fail will go on hold
on_exit_hold = (ExitCode =!= 0)
on_exit_hold_subcode = 1
on_exit_hold_reason = "Nonzero exit-code"

# periodically release failed jobs up to 5 times the hold reason code will be 3, and the subcode (set above) will be 1
# auto release jobs that fail to transfer files from squid (hold reason code 12, subcode 0)
periodic_release = ((NumJobStarts < 5) && (HoldReasonCode == 13) && ((CurrentTime - EnteredCurrentStatus) > 600)) || ((NumJobStarts < 5) && (HoldReasonCode == 3) && (HoldReasonSubCode == 1) && ( (CurrentTime - EnteredCurrentStatus) > 600))

queue $ENV(NUM_JOBS)


